version: '3.8'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile-symfony
    image: area_symfony:latest
    container_name: ${CONTAINER_NAME_PREFIX}server
    restart: unless-stopped
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=mysql://root:${MARIADB_ROOT_PASSWORD}@areadb:3306/${MARIADB_DATABASE}
    networks:
      - areadb_network
      - backend_network
    depends_on:
      - areadb

  client_web:
    build:
      context: ./area
      dockerfile: Dockerfile-reactjs
    image: area_reactjs:latest
    container_name: ${CONTAINER_NAME_PREFIX}client_web
    restart: unless-stopped
    ports:
      - 8081:3000
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - server

  areadb:
    image: mariadb
    container_name: ${CONTAINER_NAME_PREFIX}db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql/
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    networks:
      - areadb_network
      - backend_network

  phpmyadmin:
    image: phpmyadmin
    container_name: ${CONTAINER_NAME_PREFIX}db_admin
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - areadb_network
    depends_on:
      - areadb

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${VOLUME_DATABASE}'

networks:
  frontend_network:
  backend_network:
  areadb_network: