# USER
user_register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]
user_login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

# SPOTIFY
spotify_api_connect:
    path: /spotify/connect
    controller: App\Controller\SpotifyAPIController::connect
    methods: [POST]
spotify_api_get_access_token:
    path: /spotify/get_access_token
    controller: App\Controller\SpotifyAPIController::getAccessToken
    methods: [POST]
spotify_api_refresh_access_token:
    path: /spotify/refresh_access_token
    controller: App\Controller\SpotifyAPIController::refreshAccessToken
spotify_api_search:
    path: /spotify/search
    controller: App\Controller\SpotifyAPIController::search
spotify_api_get_user_playlists:
    path: /spotify/get_user_playlists
    controller: App\Controller\SpotifyAPIController::getUserPlaylists
spotify_api_check_music_playlist:
    path: /spotify/action/check_music_playlist
    controller: App\Controller\SpotifyAPIController::isMusicAddedToPlaylist
    methods: [POST]
spotify_api_check_music_playlist_parameters:
    path: /spotify/action/check_music_playlist/get_parameters
    controller: App\Controller\SpotifyAPIController::getIsMusicAddedToPlaylistParameters
    methods: [POST]
spotify_api_reaction_change_playlist_details:
    path: /spotify/reaction/change_playlist_details
    controller: App\Controller\SpotifyAPIController::changePlaylistDetails
    methods: [POST]
spotify_api_reaction_add_artist_music_to_playlist:
    path: /spotify/reaction/add_artist_music_to_playlist
    controller: App\Controller\SpotifyAPIController::addMusicFromArtistListToPlaylist
    methods: [POST]

# AUTOMATION
automation_add:
    path: /automation/add
    controller: App\Controller\AutomationController::addAutomation
automation_get:
    path: /automation/get
    controller: App\Controller\AutomationController::getAutomation
automation_edit:
    path: /automation/edit
    controller: App\Controller\AutomationController::editAutomation

# ACTION
action_get_all:
    path: /action/get_all
    controller: App\Controller\ActionController::getAllActions

# AUTOMATION ACTION
automation_reaction_trigger:
    path: /automation/reaction/trigger
    controller: App\Controller\AutomationActionController::triggerReaction
automation_reaction_do:
    path: /automation/reaction/do
    controller: App\Controller\AutomationActionController::doReaction
automation_action_check_all:
    path: /automation/action/check_all
    controller: App\Controller\AutomationActionController::checkAllActions
