# USER
user_register:
  path: /register
  controller: App\Controller\UserController::register
  methods: [POST]
user_login:
  path: /login
  controller: App\Controller\UserController::login
  methods: [POST]

# SPOTIFY
spotify_api_connect:
  path: /spotify/connect
  controller: App\Controller\SpotifyAPIController::connect
  methods: [POST]
spotify_api_get_access_token:
  path: /spotify/get_access_token
  controller: App\Controller\SpotifyAPIController::getAccessToken
  methods: [POST]
spotify_api_refresh_access_token:
  path: /spotify/refresh_access_token
  controller: App\Controller\SpotifyAPIController::refreshAccessToken
  methods: [POST]
spotify_api_search:
  path: /spotify/search
  controller: App\Controller\SpotifyAPIController::search
  methods: [POST]
spotify_api_get_user_playlists:
  path: /spotify/get_user_playlists
  controller: App\Controller\SpotifyAPIController::getUserPlaylists
  methods: [POST]
spotify_api_check_music_playlist:
  path: /spotify/action/check_music_playlist
  controller: App\Controller\SpotifyAPIController::isMusicAddedToPlaylist
  methods: [POST]
spotify_api_check_music_playlist_parameters:
  path: /spotify/action/check_music_playlist/get_parameters
  controller: App\Controller\SpotifyAPIController::getIsMusicAddedToPlaylistParameters
  methods: [POST]
spotify_api_reaction_change_playlist_details:
  path: /spotify/reaction/change_playlist_details
  controller: App\Controller\SpotifyAPIController::changePlaylistDetails
  methods: [POST]
spotify_api_reaction_add_artist_music_to_playlist:
  path: /spotify/reaction/add_artist_music_to_playlist
  controller: App\Controller\SpotifyAPIController::addMusicFromArtistListToPlaylist
  methods: [POST]

# DISCORD
discord_api_connect:
  path: /discord/connect
  controller: App\Controller\DiscordAPIController::connect
discord_api_get_access_token:
  path: /discord/get_access_token
  controller: App\Controller\DiscordAPIController::getAccessToken
discord_api_send_channel:
  path: /discord/send_channel_message
  controller: App\Controller\DiscordAPIController::sendChannelMessage

# AUTOMATION
automation_add:
  path: /automation/add
  controller: App\Controller\AutomationController::addAutomation
  methods: [POST]
automation_get:
  path: /automation/get
  controller: App\Controller\AutomationController::getAutomation
  methods: [POST]
automation_edit:
  path: /automation/edit
  controller: App\Controller\AutomationController::editAutomation
  methods: [POST]

# ACTION
action_get_all:
  path: /action/get_all
  controller: App\Controller\ActionController::getAllActions
  methods: [POST]

# AUTOMATION ACTION
automation_reaction_trigger:
  path: /automation/reaction/trigger
  controller: App\Controller\AutomationActionController::triggerReaction
  methods: [POST]
automation_reaction_do:
  path: /automation/reaction/do
  controller: App\Controller\AutomationActionController::doReaction
  methods: [POST]
automation_action_checks:
  path: /automation/action/check
  controller: App\Controller\AutomationActionController::check
