export const darkGray = "#686f84"
export const lightGray = "#ebebeb"
export const lightPurple = "#9966ff"
export const darkPurple = "#784ecc"
export const black = "#373b48"
export const white = "#ffffff"