name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: mirroring & updating
        run: |
          cd .git
          git remote update
          git push --mirror