name: Continuous Integration

on:
  push:
    branches: [ "main" ]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:Morvince/AREA.git"
          source_branch: "main"
          destination_repo: "destination_org/repository"
          destination_branch: "main"