name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: mirroring & updating
        run: |
          git clone https://Morvince:${{secrets.TOKEN}}@github.com/EpitechPromo2025/B-DEV-500-NAN-5-2-area-enzo.laurent.git
          cd B-DEV-500-NAN-5-2-area-enzo.laurent.git
          git remote update
          git push --mirror